### ISSUE TITLE
Help file example code error - rangemap_fig.R

### ISSUE THREAD

**Issue by Azamlynny** [marlonecobos/rangemap#5]
The following is the output of the rangemap_fig.R example code:

```
> # getting the data from GBIF
> species <- name_lookup(query = "Dasypus kappleri",
+                        rank="species", return = "data") # information about the species
> 
> for (i in 1:length(species$key)) {
+   cat("key", (1:length(species$key))[i], "=",
+       occ_count(taxonKey = species$key[i], georeferenced = TRUE), "\n")
+ }
Error: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 Server Error</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /occurrence/count. Reason:
<pre>    Server Error</pre></p><h3>Caused by:</h3><pre>org.cache2k.integration.CacheLoaderException: expiry=2019-12-05 23:00:55.631, cause: ElasticsearchStatusException[Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]]
	at org.cache2k.core.StandardExceptionPropagator.propagateException(StandardExceptionPropagator.java:48)
	at org.cache2k.core.HeapCache.returnValue(HeapCache.java:1256)
	at org.cache2k.core.HeapCache.get(HeapCache.java:552)
	at org.gbif.metrics.es.EsMetricsService.count(EsMetricsService.java:218)
	at org.gbif.metrics.ws.resources.OccurrenceCubeResource.count(OccurrenceCubeResource.java:55)
	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethod
```

Another error arises later on: 
```
> # keeping only georeferenced records
> occ_g <- occ[!is.na(occ$decimalLatitude) & !is.na(occ$decimalLongitude),
+              c("name", "decimalLongitude", "decimalLatitude")]
Error in occ$decimalLatitude : $ operator is invalid for atomic vectors
```

**Comment by Azamlynny** [comment]
### Session Info:
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] maptools_0.9-9 maps_3.3.0     raster_3.0-7   sp_1.3-2       rgbif_1.4.0   

<details><summary>loaded via a namespace (and not attached):</summary>
<p>
 [1] httr_1.4.1              
rnaturalearth_0.1.0    
 tidyr_1.0.0             
jsonlite_1.6           
 [5] viridisLite_0.3.0    
   shiny_1.4.0         
    assertthat_0.2.1
        triebeard_0.3.0        
 [9] urltools_1.7.3     
     yaml_2.2.0         
    pillar_1.4.2          
  backports_1.1.5        
[13] lattice_0.20-38  
       glue_1.3.1          
    digest_0.6.23        
   manipulateWidget_0.10.0
[17] promises_1.1.0   
       colorspace_1.4-1  
      htmltools_0.4.0 
        httpuv_1.5.2           
[21] plyr_1.8.4    
          pkgconfig_2.0.3 
        oai_0.3.0   
            httpcode_0.2.0         
[25] purrr_0.3.3   
          xtable_1.8-4    
        scales_1.1.0    
        webshot_0.5.2          
[29] whisker_0.4    
         later_1.0.0   
          tibble_2.1.3  
          spatial_7.3-11         
[33] farver_2.0.1     
       ggplot2_3.2.1  
         lazyeval_0.2.2 
         magrittr_1.5           
[37] crayon_1.3.4    
        mime_0.7       
         xml2_1.2.2      
        foreign_0.8-71         
[41] class_7.3-15   
         tools_3.6.1    
         data.table_1.12.6   
    lifecycle_0.1.0        
[45] stringr_1.4.0 
          V8_2.3       
           plotly_4.9.1  
          munsell_0.5.0          
[49] geoaxe_0.1.0    
        compiler_3.6.1  
        e1071_1.7-3    
         concaveman_1.0.0       
[53] rlang_0.4.2  
           classInt_0.4-2 
         units_0.6-5      
       grid_3.6.1             
[57] rstudioapi_0.10    
     htmlwidgets_1.5.1  
     crosstalk_1.0.0       
  miniUI_0.1.1.1         
[61] gtable_0.3.0      
      codetools_0.2-16   
     DBI_1.0.0          
     curl_4.2               
[65] R6_2.4.1         
       knitr_1.26       
       dplyr_0.8.3      
       rgdal_1.4-8            
[69] fastmap_1.0.1  
         rgeos_0.5-2      
       zeallot_0.1.0       
    KernSmooth_2.23-15     
[73] stringi_1.4.3      
     crul_0.9.0          
    Rcpp_1.0.3         
     vctrs_0.2.0            
[77] sf_0.8-0           
     rgl_0.100.30       
     tidyselect_0.2.5   
     xfun_0.11 
</p>
</details>

**Comment by marlonecobos** [comment]
Thanks, @Azamlynny, the error is fixed. I excluded code from the example that was producing the error and fixed the key for searching the species data. Further errors were caused by the absence of GBF data when using the previous key.
